//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoTrader.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductKeywords
    {
        public int Id { get; set; }
        public int Product { get; set; }
        public string Keyword { get; set; }
        public Nullable<double> Weight { get; set; }
    
        public virtual Product Product1 { get; set; }
    }
}
